"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, CircleAlert, Compass, Heart, LogOut, MessageCircle, Plus, RefreshCw, Send, ShieldCheck, Sparkles, UsersRound, Wrench, X, Zap } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";
import { getSupabaseClient, isSupabaseConfigured } from "../lib/supabase/client";
import type { Candidate, Connection, Message, Profile, Project, ProjectTask } from "../lib/supabase/models";

type View = "meet" | "connections" | "builds" | "profile";
type MeetMessage = { id: string; sender_id: string; body: string; created_at: string };
type UserSession = { user: { id: string; email?: string; email_confirmed_at?: string } };
const configured = isSupabaseConfigured();
const initials = (name: string) => name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(value));

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="cf-field"><span>{label}</span>{children}</label>; }

export default function ConfluxApp() {
  const pathname = usePathname();
  return pathname === "/" ? <MarketingLanding /> : <ProductApp />;
}

function ProductApp() {
  const pathname = usePathname();
  const router = useRouter();
  const supabase = useMemo(() => configured ? getSupabaseClient() : null, []);
  const viewForPath: Record<string, View> = { "/meet": "meet", "/connections": "connections", "/build-rooms": "builds", "/profile": "profile" };
  const [view, setView] = useState<View>(viewForPath[pathname] ?? "meet");
  const [session, setSession] = useState<UserSession | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [booting, setBooting] = useState(true);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const loadProfile = useCallback(async (userId: string) => {
    if (!supabase) return;
    const { data, error: profileError } = await supabase.from("cf_profiles").select("*").eq("id", userId).maybeSingle();
    if (profileError) setError(profileError.message);
    setProfile((data as Profile | null) ?? null);
  }, [supabase]);
  useEffect(() => {
    if (!supabase) { setBooting(false); return; }
    let active = true;
    void supabase.auth.getSession().then(async ({ data: { session: nextSession } }) => { if (!active) return; setSession(nextSession as typeof session); if (nextSession) await loadProfile(nextSession.user.id); if (active) setBooting(false); });
    const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => { setSession(nextSession as typeof session); setProfile(null); if (nextSession) void loadProfile(nextSession.user.id); });
    return () => { active = false; listener.subscription.unsubscribe(); };
  }, [loadProfile, supabase]);
  useEffect(() => { if (!notice) return; const id = window.setTimeout(() => setNotice(""), 3600); return () => window.clearTimeout(id); }, [notice]);
  useEffect(() => { setView(viewForPath[pathname] ?? "meet"); }, [pathname]);
  if (booting) return <main className="cf-loading"><span className="cf-pulse" />Opening CONFLUX</main>;
  if (!configured) return <ConnectionRequired />;
  if (!session) return <Auth onError={setError} />;
  if (!profile || !profile.onboarding_complete) return <NeedsOnboarding />;
  const client = supabase!;
  const nav: Array<[View, string, typeof Zap]> = [["meet", "Meet", Zap], ["connections", "Connections", UsersRound], ["builds", "Build rooms", Wrench], ["profile", "Profile", Compass]];
  const routes: Record<View, string> = { meet: "/meet", connections: "/connections", builds: "/build-rooms", profile: "/profile" };
  return <main className="cf-app"><aside className="cf-sidebar"><button className="cf-brand" onClick={() => router.push("/")} aria-label="CONFLUX home">CONFLUX<span>.</span></button><p className="cf-status"><i />Intentional introductions</p><nav aria-label="Primary navigation">{nav.map(([key, label, Icon]) => <button key={key} className={view === key ? "active" : ""} onClick={() => router.push(routes[key])}><Icon size={18} />{label}</button>)}</nav><div className="cf-account"><span className="cf-avatar">{initials(profile.full_name)}</span><span><strong>{profile.full_name}</strong><small>{profile.email_verified ? "Verified member" : "Email pending"}</small></span></div></aside><section className="cf-main"><header className="cf-topbar"><span className="cf-kicker">{view === "meet" ? "Live introductions" : view === "connections" ? "Mutual connections" : view === "builds" ? "Shared work" : "Your builder identity"}</span><button className="cf-quiet" onClick={() => void client.auth.signOut()}><LogOut size={16} />Sign out</button></header><div className="cf-content">{error && <div className="cf-alert error"><CircleAlert size={18} /><span>{error}</span><button onClick={() => setError("")} aria-label="Dismiss error"><X size={17} /></button></div>}{notice && <div className="cf-alert success"><Check size={18} /><span>{notice}</span></div>}{view === "meet" && <Meet userId={session.user.id} onNotice={setNotice} onError={setError} onConnected={() => router.push("/connections")} />}{view === "connections" && <Connections userId={session.user.id} onError={setError} onOpenBuild={() => router.push("/build-rooms")} />}{view === "builds" && <BuildRooms userId={session.user.id} onError={setError} onNotice={setNotice} />}{view === "profile" && <ProfileEditor profile={profile} email={session.user.email ?? ""} onSaved={loadProfile} onError={setError} onNotice={setNotice} />}</div></section></main>;
}

function ConnectionRequired() { return <main className="cf-gate"><section><span className="cf-orb">↗</span><p className="cf-kicker">Deployment setup required</p><h1>Connect this build<br />to its real data.</h1><p>CONFLUX will not show sample people or pretend conversations. Add the public Supabase URL and anon key in Vercel, then redeploy.</p><code>NEXT_PUBLIC_SUPABASE_URL<br />NEXT_PUBLIC_SUPABASE_ANON_KEY</code><small>Keep service-role credentials only on a trusted server or Supabase Edge Function.</small></section></main>; }

function NeedsOnboarding() {
  const router = useRouter();
  useEffect(() => { router.replace("/onboarding"); }, [router]);
  return <main className="cf-loading"><span className="cf-pulse" />Opening your profile setup</main>;
}

function Auth({ onError }: { onError: (message: string) => void }) {
  const supabase = getSupabaseClient(); const [mode, setMode] = useState<"signin" | "signup">("signin"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [working, setWorking] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setWorking(true); onError(""); const result = mode === "signin" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { emailRedirectTo: `${window.location.origin}/` } }); setWorking(false); if (result.error) onError(result.error.message); };
  return <main className="cf-auth"><section><button className="cf-brand" aria-label="CONFLUX">CONFLUX<span>.</span></button><p className="cf-kicker">People behind what gets built</p><h1>Build with more<br />than a profile.</h1><p>Start with a real identity, a useful conversation, and mutual intent.</p><form onSubmit={submit}><Field label="Email"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /></Field><Field label="Password"><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={8} autoComplete={mode === "signin" ? "current-password" : "new-password"} /></Field><button className="cf-primary" disabled={working}>{working ? "Working…" : mode === "signin" ? "Sign in" : "Create account"}<ArrowRight size={17} /></button></form><button className="cf-text-button" onClick={() => setMode(mode === "signin" ? "signup" : "signin")}>{mode === "signin" ? "New here? Create an account" : "Already a member? Sign in"}</button></section><aside><span>“The right build partner is usually one honest conversation away.”</span></aside></main>;
}

function Onboarding({ session, initial, onComplete, onError }: { session: UserSession; initial: Profile | null; onComplete: (id: string) => Promise<void>; onError: (message: string) => void }) {
  const supabase = getSupabaseClient(); const [name, setName] = useState(initial?.full_name ?? ""); const [username, setUsername] = useState(initial?.username ?? ""); const [headline, setHeadline] = useState(initial?.headline ?? ""); const [skills, setSkills] = useState(initial?.skills.join(", ") ?? ""); const [build, setBuild] = useState(initial?.current_build ?? ""); const [lookingFor, setLookingFor] = useState(initial?.looking_for ?? ""); const [working, setWorking] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setWorking(true); onError(""); const cleanSkills = skills.split(",").map((skill) => skill.trim()).filter(Boolean).slice(0, 8); const { error } = await supabase.from("cf_profiles").upsert({ id: session.user.id, username: username.trim(), full_name: name.trim(), headline: headline.trim() || null, skills: cleanSkills, current_build: build.trim() || null, looking_for: lookingFor.trim() || null, email_verified: Boolean(session.user.email_confirmed_at), onboarding_complete: true, is_discoverable: true }); setWorking(false); if (error) { onError(error.message); return; } await onComplete(session.user.id); };
  return <main className="cf-onboarding"><form onSubmit={submit}><button className="cf-brand" type="button">CONFLUX<span>.</span></button><p className="cf-kicker">Set the signal</p><h1>Give a first conversation a head start.</h1><p>Keep it compact. Your contact links stay private until you both choose Connect.</p><div className="cf-form-grid"><Field label="Your name"><input value={name} onChange={(e) => setName(e.target.value)} required maxLength={120} /></Field><Field label="Username"><input value={username} onChange={(e) => setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, ""))} required minLength={3} maxLength={30} /></Field><Field label="What do you build?"><input value={headline} onChange={(e) => setHeadline(e.target.value)} placeholder="Product engineer building helpful tools" maxLength={180} /></Field><Field label="Skills, separated by commas"><input value={skills} onChange={(e) => setSkills(e.target.value)} placeholder="React, design systems, AI" /></Field><Field label="What is moving right now?"><textarea value={build} onChange={(e) => setBuild(e.target.value)} placeholder="A sentence is plenty." maxLength={240} /></Field><Field label="Who would be useful to meet?"><textarea value={lookingFor} onChange={(e) => setLookingFor(e.target.value)} placeholder="A collaborator, feedback, or a new perspective." maxLength={240} /></Field></div><button className="cf-primary" disabled={working}>{working ? "Saving…" : "Enter CONFLUX"}<ArrowRight size={17} /></button></form></main>;
}

function CandidateCard({ candidate, compact = false }: { candidate: Candidate; compact?: boolean }) { return <article className={`cf-person ${compact ? "compact" : ""}`}><span className="cf-avatar large">{initials(candidate.full_name)}</span><div><div className="cf-person-title"><h2>{candidate.full_name}</h2>{candidate.email_verified && <ShieldCheck size={16} aria-label="Email verified" />}</div><p>{candidate.headline || candidate.experience_band || "Builder"}{candidate.city ? ` · ${candidate.city}` : ""}</p>{candidate.match_reason && <strong className="cf-match">{candidate.match_reason}</strong>}</div>{candidate.skills.length > 0 && <div className="cf-chips">{candidate.skills.slice(0, 4).map((skill) => <span key={skill}>{skill}</span>)}</div>} {!compact && <div className="cf-person-context"><b>{candidate.current_build ? "Building" : "Looking for"}</b><p>{candidate.current_build || candidate.looking_for || "Open to a useful introduction."}</p></div>}</article>; }

function Meet({ userId, onNotice, onError, onConnected }: { userId: string; onNotice: (message: string) => void; onError: (message: string) => void; onConnected: () => void }) {
  const supabase = getSupabaseClient(); const [candidate, setCandidate] = useState<Candidate | null>(null); const [sessionId, setSessionId] = useState<string | null>(null); const [messages, setMessages] = useState<MeetMessage[]>([]); const [draft, setDraft] = useState(""); const [loading, setLoading] = useState(false); const [decision, setDecision] = useState<"CONNECT" | "NEXT" | null>(null); const [safetyOpen, setSafetyOpen] = useState(false);
  const discover = useCallback(async () => { setLoading(true); setCandidate(null); setSessionId(null); setMessages([]); setDecision(null); onError(""); const { data, error } = await supabase.rpc("cf_discover_profiles", { result_limit: 1 }); setLoading(false); if (error) { onError(error.message); return; } setCandidate(((data as Candidate[]) ?? [])[0] ?? null); }, [onError, supabase]);
  const start = async () => { if (!candidate) return; setLoading(true); const { data, error } = await supabase.rpc("cf_open_meet", { candidate_id: candidate.id }); setLoading(false); if (error) { onError(error.message); return; } const id = data as string; setSessionId(id); const { data: history, error: historyError } = await supabase.from("cf_meet_messages").select("*").eq("meet_session_id", id).order("created_at"); if (historyError) onError(historyError.message); else setMessages((history as MeetMessage[]) ?? []); };
  useEffect(() => { if (!sessionId) return; const channel = supabase.channel(`meet:${sessionId}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "cf_meet_messages", filter: `meet_session_id=eq.${sessionId}` }, (payload) => setMessages((current) => [...current, payload.new as MeetMessage])).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [sessionId, supabase]);
  const send = async (event: FormEvent) => { event.preventDefault(); if (!sessionId || !draft.trim()) return; const body = draft.trim(); setDraft(""); const { error } = await supabase.from("cf_meet_messages").insert({ meet_session_id: sessionId, sender_id: userId, body }); if (error) { setDraft(body); onError(error.message); } };
  const choose = async (next: "CONNECT" | "NEXT") => { if (!sessionId) return; setDecision(next); const { data, error } = await supabase.rpc("cf_record_meet_decision", { session_id: sessionId, choice: next }); if (error) { setDecision(null); onError(error.message); return; } const result = Array.isArray(data) ? data[0]?.status : null; if (result === "MUTUAL_CONNECTION") { onNotice("It’s mutual — your private connection is now open."); onConnected(); } else if (next === "NEXT") onNotice("Meet ended. There is no shared contact information."); else onNotice("Connect is private until they choose it too."); };
  if (!candidate) return <section className="cf-hero"><div><p className="cf-kicker">Meet, without the scroll</p><h1>One person.<br />One real reason.</h1><p>Discovery uses your profile signals and excludes people you have blocked, skipped, or already met. Nothing is timed; leave when the conversation is complete.</p><button className="cf-primary" onClick={() => void discover()} disabled={loading}>{loading ? "Finding a fit…" : "Find a builder"}<Zap size={17} /></button></div><aside className="cf-hero-note"><Sparkles size={21} /><strong>Text is always on</strong><p>Voice and video need explicit consent. Direct contact needs a mutual Connect.</p></aside></section>;
  if (!sessionId) return <section className="cf-meet"><div className="cf-section-heading"><button className="cf-back" onClick={() => setCandidate(null)}>← Back</button><p className="cf-kicker">A possible introduction</p></div><CandidateCard candidate={candidate} /><div className="cf-meet-actions"><button className="cf-secondary" onClick={() => void discover()} disabled={loading}><RefreshCw size={17} />Someone else</button><button className="cf-primary" onClick={() => void start()} disabled={loading}>Start text-first Meet<ArrowRight size={17} /></button></div><p className="cf-footnote">You both decide privately whether this becomes a connection.</p></section>;
  return <section className="cf-live-meet"><header><div><p className="cf-kicker">Live Meet · no clock</p><CandidateCard candidate={candidate} compact /></div><span className="cf-live"><i />Live</span></header><div className="cf-chat" aria-live="polite">{messages.length ? messages.map((message) => <p className={message.sender_id === userId ? "mine" : "theirs"} key={message.id}>{message.body}</p>) : <div className="cf-empty-small"><MessageCircle size={22} />Say hello. Text is here even if you later choose voice or video.</div>}</div><form className="cf-compose" onSubmit={send}><input value={draft} onChange={(e) => setDraft(e.target.value)} maxLength={2000} placeholder="Write a thoughtful first message" /><button aria-label="Send message"><Send size={18} /></button></form>{safetyOpen && <SafetyActions subjectId={candidate.id} onClose={() => setSafetyOpen(false)} onNotice={onNotice} onError={onError} />}<footer><button className="cf-quiet" onClick={() => setSafetyOpen(true)}>Safety</button><span /><button className={decision === "NEXT" ? "chosen next" : "cf-secondary"} onClick={() => void choose("NEXT")} disabled={Boolean(decision)}>End and Next</button><button className={decision === "CONNECT" ? "chosen connect" : "cf-primary"} onClick={() => void choose("CONNECT")} disabled={Boolean(decision)}>Connect privately <ArrowRight size={16} /></button></footer></section>;
}

function SafetyActions({ subjectId, onClose, onNotice, onError }: { subjectId: string; onClose: () => void; onNotice: (message: string) => void; onError: (message: string) => void }) {
  const supabase = getSupabaseClient(); const [reason, setReason] = useState("SAFETY"); const [detail, setDetail] = useState(""); const [working, setWorking] = useState(false);
  const report = async () => { setWorking(true); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setWorking(false); onError("Your session has expired."); return; } const { error } = await supabase.from("cf_reports").insert({ reporter_id: user.id, subject_id: subjectId, reason, detail: detail.trim() || null }); setWorking(false); if (error) { onError(error.message); return; } onClose(); onNotice("Report received privately. Thank you for helping keep CONFLUX safe."); };
  const block = async () => { setWorking(true); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setWorking(false); onError("Your session has expired."); return; } const { error } = await supabase.from("cf_blocks").upsert({ blocker_id: user.id, blocked_id: subjectId }); setWorking(false); if (error) { onError(error.message); return; } onClose(); onNotice("Blocked. They will not appear in future discovery."); };
  return <div className="cf-safety"><header><strong>Your space, your call.</strong><button onClick={onClose} aria-label="Close safety actions"><X size={16} /></button></header><p>End a Meet, report, or block without sharing your choice with the other person.</p><label>Report reason<select value={reason} onChange={(event) => setReason(event.target.value)}><option value="SAFETY">Safety concern</option><option value="HARASSMENT">Harassment or hate</option><option value="SPAM">Spam or scam</option><option value="IMPERSONATION">Impersonation</option><option value="OTHER">Something else</option></select></label><textarea value={detail} onChange={(event) => setDetail(event.target.value)} placeholder="Optional details" maxLength={1200} /><div><button className="cf-secondary" onClick={() => void block()} disabled={working}>Block person</button><button className="cf-primary" onClick={() => void report()} disabled={working}>{working ? "Saving…" : "Send private report"}</button></div></div>;
}

function Connections({ userId, onError, onOpenBuild }: { userId: string; onError: (message: string) => void; onOpenBuild: () => void }) {
  const supabase = getSupabaseClient(); const [connections, setConnections] = useState<Connection[]>([]); const [selected, setSelected] = useState<Connection | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [draft, setDraft] = useState("");
  const load = useCallback(async () => { const { data, error } = await supabase.from("cf_connections").select("*").or(`low_profile_id.eq.${userId},high_profile_id.eq.${userId}`).order("created_at", { ascending: false }); if (error) { onError(error.message); return; } const rows = (data as Connection[]) ?? []; const otherIds = rows.map((row) => row.low_profile_id === userId ? row.high_profile_id : row.low_profile_id); const { data: people, error: peopleError } = otherIds.length ? await supabase.from("cf_profiles").select("*").in("id", otherIds) : { data: [], error: null }; if (peopleError) onError(peopleError.message); const profiles = new Map(((people as Profile[]) ?? []).map((person) => [person.id, person])); setConnections(rows.map((row) => ({ ...row, other: profiles.get(row.low_profile_id === userId ? row.high_profile_id : row.low_profile_id) }))); }, [onError, supabase, userId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!selected) return; void supabase.from("cf_messages").select("*").eq("connection_id", selected.id).is("deleted_at", null).order("created_at").then(({ data, error }) => { if (error) onError(error.message); else setMessages((data as Message[]) ?? []); }); const channel = supabase.channel(`connection:${selected.id}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "cf_messages", filter: `connection_id=eq.${selected.id}` }, (payload) => setMessages((current) => [...current, payload.new as Message])).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [onError, selected, supabase]);
  const send = async (event: FormEvent) => { event.preventDefault(); if (!selected || !draft.trim()) return; const body = draft.trim(); setDraft(""); const { error } = await supabase.from("cf_messages").insert({ connection_id: selected.id, sender_id: userId, body }); if (error) { setDraft(body); onError(error.message); } };
  return <section className="cf-split"><div className="cf-list-pane"><p className="cf-kicker">Mutual, not accumulated</p><h1>Connections</h1>{connections.length ? <div className="cf-connection-list">{connections.map((connection) => <button key={connection.id} className={selected?.id === connection.id ? "active" : ""} onClick={() => setSelected(connection)}><span className="cf-avatar">{initials(connection.other?.full_name ?? "?")}</span><span><strong>{connection.other?.full_name ?? "Private connection"}</strong><small>Met {formatDate(connection.created_at)}</small></span></button>)}</div> : <Empty icon={<UsersRound size={25} />} title="No mutual connections yet" body="When both people choose Connect after a Meet, the conversation appears here." />}</div><div className="cf-thread">{selected ? <><header><span className="cf-avatar">{initials(selected.other?.full_name ?? "?")}</span><div><h2>{selected.other?.full_name}</h2><p>Mutual connection</p></div><button className="cf-quiet" onClick={onOpenBuild}><Wrench size={16} />Build together</button></header><div className="cf-chat">{messages.length ? messages.map((message) => <p className={message.sender_id === userId ? "mine" : "theirs"} key={message.id}>{message.body}</p>) : <div className="cf-empty-small"><MessageCircle size={22} />This is a real, private thread. Start with what you want to move forward.</div>}</div><form className="cf-compose" onSubmit={send}><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Message your connection" maxLength={4000} /><button aria-label="Send message"><Send size={18} /></button></form></> : <div className="cf-thread-empty"><MessageCircle size={31} /><h2>Choose a connection</h2><p>Only people who chose you back can start a thread.</p></div>}</div></section>;
}

function BuildRooms({ userId, onError, onNotice }: { userId: string; onError: (message: string) => void; onNotice: (message: string) => void }) {
  const supabase = getSupabaseClient(); const [projects, setProjects] = useState<Project[]>([]); const [selected, setSelected] = useState<Project | null>(null); const [tasks, setTasks] = useState<ProjectTask[]>([]); const [creating, setCreating] = useState(false); const [name, setName] = useState(""); const [idea, setIdea] = useState(""); const [taskTitle, setTaskTitle] = useState("");
  const load = useCallback(async () => { const { data, error } = await supabase.from("cf_projects").select("*").is("archived_at", null).order("updated_at", { ascending: false }); if (error) onError(error.message); else setProjects((data as Project[]) ?? []); }, [onError, supabase]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (!selected) return; void supabase.from("cf_project_tasks").select("*").eq("project_id", selected.id).order("created_at").then(({ data, error }) => { if (error) onError(error.message); else setTasks((data as ProjectTask[]) ?? []); }); }, [onError, selected, supabase]);
  const create = async (event: FormEvent) => { event.preventDefault(); const { data, error } = await supabase.from("cf_projects").insert({ owner_id: userId, name: name.trim(), idea: idea.trim() }).select().single(); if (error) { onError(error.message); return; } setName(""); setIdea(""); setCreating(false); await load(); setSelected(data as Project); onNotice("Build Room created. Add one useful next step."); };
  const addTask = async (event: FormEvent) => { event.preventDefault(); if (!selected || !taskTitle.trim()) return; const { error } = await supabase.from("cf_project_tasks").insert({ project_id: selected.id, title: taskTitle.trim() }); if (error) { onError(error.message); return; } setTaskTitle(""); const { data } = await supabase.from("cf_project_tasks").select("*").eq("project_id", selected.id).order("created_at"); setTasks((data as ProjectTask[]) ?? []); };
  const toggleTask = async (task: ProjectTask) => { const status = task.status === "DONE" ? "TODO" : "DONE"; const { error } = await supabase.from("cf_project_tasks").update({ status }).eq("id", task.id); if (error) onError(error.message); else setTasks((current) => current.map((item) => item.id === task.id ? { ...item, status } : item)); };
  return <section className="cf-builds"><header><div><p className="cf-kicker">A room for real work</p><h1>Build rooms</h1><p>Your basic room is yours to run. Invite collaborators through a mutual connection, then make progress visible.</p></div><button className="cf-primary" onClick={() => setCreating(true)}><Plus size={17} />New room</button></header>{creating && <form className="cf-inline-form" onSubmit={create}><Field label="Room name"><input value={name} onChange={(e) => setName(e.target.value)} required maxLength={160} placeholder="What are you building?" /></Field><Field label="The idea"><input value={idea} onChange={(e) => setIdea(e.target.value)} required maxLength={280} placeholder="A concise problem or promise" /></Field><button className="cf-primary">Create</button><button type="button" className="cf-quiet" onClick={() => setCreating(false)}>Cancel</button></form>}<div className="cf-build-layout"><div className="cf-project-list">{projects.length ? projects.map((project) => <button key={project.id} className={selected?.id === project.id ? "active" : ""} onClick={() => setSelected(project)}><span>{project.stage}</span><strong>{project.name}</strong><small>{project.idea}</small></button>) : <Empty icon={<Wrench size={25} />} title="Nothing in progress yet" body="Start a room for a real idea, then add the next concrete task." />}</div><div className="cf-project-detail">{selected ? <><p className="cf-kicker">{selected.stage}</p><h2>{selected.name}</h2><p>{selected.idea}</p><div className="cf-task-list">{tasks.length ? tasks.map((task) => <button onClick={() => void toggleTask(task)} key={task.id}><i className={task.status === "DONE" ? "done" : ""}>{task.status === "DONE" && <Check size={12} />}</i><span>{task.title}</span></button>) : <p className="cf-empty-copy">No tasks yet. A small, clear first task beats a long wishlist.</p>}</div><form className="cf-add-task" onSubmit={addTask}><input value={taskTitle} onChange={(e) => setTaskTitle(e.target.value)} placeholder="Add the next step" maxLength={240} /><button aria-label="Add task"><Plus size={18} /></button></form></> : <div className="cf-thread-empty"><Wrench size={31} /><h2>Open a room</h2><p>Select a room to see its actual tasks.</p></div>}</div></div></section>;
}

function ProfileEditor({ profile, email, onSaved, onError, onNotice }: { profile: Profile; email: string; onSaved: (id: string) => Promise<void>; onError: (message: string) => void; onNotice: (message: string) => void }) {
  const supabase = getSupabaseClient(); const [form, setForm] = useState({ full_name: profile.full_name, headline: profile.headline ?? "", city: profile.city ?? "", skills: profile.skills.join(", "), current_build: profile.current_build ?? "", looking_for: profile.looking_for ?? "", is_discoverable: profile.is_discoverable }); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); const { error } = await supabase.from("cf_profiles").update({ full_name: form.full_name.trim(), headline: form.headline.trim() || null, city: form.city.trim() || null, skills: form.skills.split(",").map((value) => value.trim()).filter(Boolean).slice(0, 8), current_build: form.current_build.trim() || null, looking_for: form.looking_for.trim() || null, is_discoverable: form.is_discoverable }).eq("id", profile.id); setSaving(false); if (error) { onError(error.message); return; } await onSaved(profile.id); onNotice("Profile updated."); };
  return <section className="cf-profile"><header><span className="cf-avatar xl">{initials(profile.full_name)}</span><div><p className="cf-kicker">Builder identity</p><h1>{profile.full_name}</h1><p>{email} · {profile.email_verified ? "email verified" : "verification pending"}</p></div></header><form onSubmit={submit} className="cf-profile-form"><div className="cf-form-grid"><Field label="Name"><input value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} required /></Field><Field label="City"><input value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} maxLength={100} /></Field><Field label="Headline"><input value={form.headline} onChange={(e) => setForm({ ...form, headline: e.target.value })} maxLength={180} /></Field><Field label="Skills"><input value={form.skills} onChange={(e) => setForm({ ...form, skills: e.target.value })} /></Field><Field label="Currently building"><textarea value={form.current_build} onChange={(e) => setForm({ ...form, current_build: e.target.value })} maxLength={240} /></Field><Field label="Looking for"><textarea value={form.looking_for} onChange={(e) => setForm({ ...form, looking_for: e.target.value })} maxLength={240} /></Field></div><label className="cf-switch"><input type="checkbox" checked={form.is_discoverable} onChange={(e) => setForm({ ...form, is_discoverable: e.target.checked })} /><span /><b>Available for Meet</b><small>Turn this off to pause discovery. Existing connections remain available.</small></label><button className="cf-primary" disabled={saving}>{saving ? "Saving…" : "Save profile"}<Check size={17} /></button></form></section>;
}

function Empty({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <div className="cf-empty">{icon}<h2>{title}</h2><p>{body}</p></div>; }

function MarketingLanding() {
  const router = useRouter();
  const start = () => router.push("/register");
  return <main className="landing-v2">
    <header className="v2-nav"><button className="v2-logo" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><span className="v2-mark"><i /><i /><i /></span>CONFLUX<span>.</span></button><nav><a href="#how-it-works">How it works</a><a href="#features">Features</a><button onClick={() => router.push("/auth")}>Sign in</button></nav><button className="v2-nav-cta" onClick={start}>Start meeting <ArrowRight size={16} /></button></header>
    <section className="v2-hero"><div className="v2-hero-copy"><p className="v2-label">A BETTER WAY TO MEET BUILDERS <span /></p><h1>One good conversation can change what you build.</h1><p>You can find tools anywhere. CONFLUX helps you find the people behind the ideas, experiments, and projects that move you forward.</p><div className="v2-actions"><button className="v2-primary" onClick={start}>Start a meeting <ArrowRight size={18} /></button><button className="v2-secondary" onClick={start}>Explore builders</button></div><div className="v2-proof"><span><ShieldCheck size={16} /> Verified identity</span><span><MessageCircle size={16} /> Text-first meetings</span><span><Heart size={16} /> Mutual connections</span></div></div><MarketingMoment onStart={start} /></section>
    <section className="v2-strip"><span>MEET</span><i /><span>TALK</span><i /><span>CONNECT</span><i /><span>BUILD</span><i /><span>MEET</span><i /><span>TALK</span></section>
    <section className="v2-why" id="how-it-works"><div><p className="v2-label">BUILT FOR REAL MOMENTUM</p><h2>Not another feed.<br /><em>A starting point.</em></h2></div><p>CONFLUX keeps discovery finite and gives every conversation a reason to begin. See who someone is, what they&apos;re building, and why you might click—before you say hello.</p><div className="v2-steps"><article><span>01</span><h3>Show your now</h3><p>Skills, current work, and the kind of people you want to meet.</p></article><article><span>02</span><h3>Meet without a clock</h3><p>Text first, with audio or video only when both people want it.</p></article><article><span>03</span><h3>Keep what matters</h3><p>Mutual connections become conversations, memory, and Build Rooms.</p></article></div></section>
    <section className="v2-feature-stage" id="features"><div className="v2-feature-copy"><p className="v2-label">ONE CONNECTED SYSTEM</p><h2>From “interesting person” to “let&apos;s build.”</h2><p>The experience moves naturally from discovery to conversation to collaboration, without forcing relationships to stay inside the app.</p><button className="v2-inline" onClick={start}>See your network <ArrowRight size={17} /></button></div><div className="v2-feature-window"><div className="v2-window-top"><span>YOUR CONNECTIONS</span><span>PRIVATE</span></div><div className="v2-connection"><span className="cf-avatar">MR</span><div><strong>Mutual connection</strong><small>Context stays with the people who chose it.</small></div><span>Real-time</span></div><div className="v2-memory"><small>WHY CONFLUX</small><p>Good introductions need enough signal to become useful.</p><div><span><ShieldCheck size={15} /> verified identity</span><span><Sparkles size={15} /> next step ready</span></div></div><button onClick={start}><Wrench size={17} /> Open Build Room <ArrowRight size={16} /></button></div></section>
    <section className="v2-feature-grid"><article><div className="v2-icon mint"><Compass size={22} /></div><h3>Finite discovery</h3><p>A focused dispatch of builders worth knowing, never an infinite scroll.</p><button onClick={start}>Explore people <ArrowRight size={15} /></button></article><article><div className="v2-icon lilac"><MessageCircle size={22} /></div><h3>Live Meet</h3><p>A low-pressure, text-first introduction with clear choices.</p><button onClick={start}>Enter Meet <ArrowRight size={15} /></button></article><article><div className="v2-icon peach"><Wrench size={22} /></div><h3>Build Rooms</h3><p>Turn a promising connection into clear shared work.</p><button onClick={start}>See Build Rooms <ArrowRight size={15} /></button></article></section>
    <section className="v2-trust"><div><p className="v2-label">TRUST, WITHOUT THE THEATRE</p><h2>Know who you&apos;re meeting.</h2><p>Email, LinkedIn, and GitHub verification make a first introduction more confident. You still decide what to share and whether to connect.</p></div><div className="v2-trust-stack"><span><ShieldCheck size={18} /> Email verified <Check size={17} /></span><span><ShieldCheck size={18} /> LinkedIn connected <Check size={17} /></span><span><ShieldCheck size={18} /> GitHub linked <Check size={17} /></span></div></section>
    <section className="v2-pro"><div><p className="v2-label">FREE TO MEET · PRO TO GO DEEPER</p><h2>Free helps you meet people.<br />Pro helps you build more with them.</h2></div><div><p>Meet, connect, chat, and create your own Build Room. Pro adds intentional discovery and deeper collaboration.</p><button className="v2-secondary light" onClick={start}>Explore Pro <ArrowRight size={17} /></button></div></section>
    <section className="v2-final"><p>Meet someone interesting.</p><h2>See what happens.</h2><button className="v2-primary dark" onClick={start}>Start meeting <ArrowRight size={18} /></button></section>
    <footer className="v2-footer"><button className="v2-logo" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><span className="v2-mark"><i /><i /><i /></span>CONFLUX<span>.</span></button><strong>Meet. Talk. Connect. Build.</strong><span>© CONFLUX.site</span></footer>
  </main>;
}

function MarketingMoment({ onStart }: { onStart: () => void }) {
  const [step, setStep] = useState(0);
  useEffect(() => { const cycle = window.setInterval(() => setStep((current) => (current + 1) % 3), 2800); return () => window.clearInterval(cycle); }, []);
  const copy = [["Finding someone interesting", "Checking intent, skills, and availability."], ["You both want to build AI tools", "A strong reason to meet."], ["You both connected", "A new private thread is ready."]][step];
  return <div className={`match-moment step-${step}`} aria-live="polite"><div className="match-top"><span><i /> LIVE MEET</span><strong>{step === 0 ? "SEARCHING" : step === 1 ? "READY" : "CONNECTED"}</strong></div><div className="match-people"><div className="match-person you"><span className="cf-avatar large">YU</span><strong>You</strong><small>Your intent</small></div><div className="match-link"><span><i /><i /><i /></span></div><div className="match-person maya"><span className="cf-avatar large">MB</span><strong>Builder</strong><small>Shared context</small></div></div><div className="match-copy"><span>{copy[0]}</span><strong>{copy[1]}</strong></div><div className="match-tags"><span>AI tools</span><span>Creator products</span><span>React</span></div><button onClick={onStart}>{step === 2 ? "Create your account" : "Meet a builder"} <ArrowRight size={17} /></button><div className="match-dots"><i className={step === 0 ? "active" : ""} /><i className={step === 1 ? "active" : ""} /><i className={step === 2 ? "active" : ""} /></div></div>;
}
